### ISSUE TITLE
Error during make install on MacOS (Intel CPU)

### ISSUE THREAD

**Issue by alexhansson** [acados/acados#1111]
Hello everyone,

I'm currently trying to install acados on my MacBook Pro with an Intel CPU. Everything including Cmake works, but there is an error when I try to `make install`, as outlined in the installation instructions. The following error appears:   

`error: call to undeclared library function 'malloc' with type 'void *(unsigned long)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration].
void *raw_memory_ptr = malloc(memory_size);`

I managed to work around the issue by inserting `#include <stdlib.h>` in `external/qpoases/include/qpOASES_e/MessageHandling.h`. However, I'm wondering why this error appears and how I can resolve it. I think it might have to do with the underlying C version, but I am not entirely sure.

Thanks for the help.

**Comment by FreyJo** [comment]
Hi,

this issue seems specific to the qpOASES version in acados, although you did not include the line where this occurs.
Actually, the acados qpOASES interface does not use the functions from qpOASES which use malloc inside.
Thus, we can either add the include as you suggested or comment/remove the functions that use malloc in the acados qpOASES version.
For now, I would recommend to keep the include you added or just compile `cmake -DACADOS_WITH_QPOASES=OFF ..`.

**Comment by alexhansson** [comment]
Hi @FreyJo 

Thank you very much for answering.  
I uploaded a screenshot of the occurrence (see below).
Is there any way to fix this "cleanly" from my side, especially when thinking about docker-izing the project I'm working on with acados?
<img width="1396" alt="Screenshot 2024-05-16 at 11 13 50 AM" src="https://github.com/acados/acados/assets/114674599/63a6ef47-b374-4d29-8b84-3126a4e37d31">
