### ISSUE TITLE
How is the cost at initial stage set up when using Moving horizon estimation?

### ISSUE THREAD

**Issue by kay01-kwon** [acados/acados#1190]
Hi, I'm very impressed by the acados!

I'm wondering how to implement the moving horizon estimation.

Even though I referred to the example in the python interface,

I do not understand how the initial cost is setup.

From the pendulum cart, I was able to learn about the moving horizon estimation.

I understood the noise is set as control input and the state is 

augmented to estimate unknown parameter such as the length of the cart. 

However, I'd like to know how the cost at initial stage is constructed.

Since I do not know how the cost at initial stage is constructed, 

I cannot set the dimension and the cost matrices at all for f = m*ddx/dt^2 case.

Also, I cannot find any source related to the moving horizon estimation.

Above all, I sincerely appreciate your contribution to tools for nonlinear model predictive controller.

**Comment by sandmaennchen** [comment]
Hi :wave: 
this sounds a bit like a question regarding moving horizon estimation (MHE) in general rather than a question specific to the implementation with acados. I can recommend the introductory chapters on MHE in [this textbook](https://sites.engineering.ucsb.edu/~jbraw/mpc/). 
If you have specific question on how to implement your estimator with acados, the [acados forum](https://discourse.acados.org/) is a good start for discussing with other acados users.

Best, Katrin
