### ISSUE TITLE
Parametric OCPs

### ISSUE THREAD

**Issue by nielsvd** [acados/acados#156]
It should be possible to define parametric OCPs. It could follow the model for the ``OnlineData`` data-type in acado. Hence. a parameter vector for each shooting node/interval shared across objective, system dynamics and path constraints.

**Comment by giaf** [comment]
Strictly speaking, we do not need to have the ACADO style of parameters. This is because all numerical data is parametric anyway in acados, so parameters would only affect external functions.

Whit this PR
https://github.com/acados/acados/pull/250
we added parametric casadi functions. An example is wind_turbine_example.c.

In the acados framework, this is a way smaller change (30 min of work to implement and test it) than the ACADO-way solution.

You can have a look if this satisfies your needs.
