### ISSUE TITLE
keep updating the file convention_about_external_functions.txt

### ISSUE THREAD

**Issue by giaf** [acados/acados#268]
Everyone adding/editing an external function call in acados should _immediately_ update the file
`convention_about_external_functions.txt`
https://github.com/acados/acados/blob/master/convention_about_external_functions.txt
accordingly. (at least until this finds its way into a better documentation)

@zanellia can you add the new_lifted_irk? (by the way, are you going to do for them the same that Jonathan did for irk?)
@roversch can you add the quadratic-over-nonlinear constraints, once fixed?

Thanks everyone!

**Comment by zanellia** [comment]
>
> @zanellia <https://github.com/zanellia> can you add the new_lifted_irk?
> (by the way, are you going to do for them the same that Jonathan did for
> irk?)
>

Yes, and yes :)

**Comment by giaf** [comment]
great :) thanks @zanellia !

**Comment by FreyJo** [comment]
The file was moved here:
https://github.com/acados/acados/blob/4dd0f775450af9d47615f985066c923c3d2b51c2/utils/convention_about_external_functions.txt

NOTE: It does not seem to be up to date regarding e.g. missing parameters, BGP, external functions for cost evaluation.
Anyone who is actually interested in the external functions convention should look at the generating files in the Matlab and Python interfaces which will stay up to date, since they are tested on Travis.
