### ISSUE TITLE
Matlab interface syntax

### ISSUE THREAD

**Issue by myavari** [acados/acados#340]
Hi 
I am trying to use Acados in my research. Unfortunately, I couldn't find any documentation for the Matlab interface.

I have two questions:

1- How can I change the goal state of the system? for example in ocp_nlp_example.m if I want to go to a non-zero state.
2- what are the options that I can pass to the solvers. I want to determine the constraint violation threshold and other termination criterions.

Thanks for your help

**Comment by FreyJo** [comment]
Hi,

Indeed the Matlab interface lacks documentation.
We plan to do a major revision on it, which will however take some more time.

Nevertheless, I just had a look into the source file and found the following.
In the Matlab function call
`nlp.set_stage_cost(eye(nx+nu), zeros(nx+nu), W);`
the second argument is called `y_ref` internally.
Moreover, I am pretty sure, that it should be
`zeros(nx+nu,1)`
in the matlab example, since only a vector is extracted internally.
You can try to pass your reference value there.
So try something like
`nlp.set_stage_cost(eye(nx+nu), vertcat(x_ref,u_ref), W);`

The current Matlab interface is very minimal. And as mentioned before, we are working on a full-featured interface.
Until that, you should probably consider using acados from C in order to have more options (and documentation) available.
