### ISSUE TITLE
Missing Parameter in Hessian Function 

### ISSUE THREAD

**Issue by kabzo** [acados/acados#575]
Hello,

when I try to generate a `NONLINEAR_LS` cost with e.g. quadratic term (x1**2). I get error during generation saying: 
```RuntimeError: .../casadi/core/sx_function.cpp:149: Code generation of '***' is not possible since variables [y_6, y_0] are free.```
This looks like is happening because in this line
https://github.com/acados/acados/blob/master/interfaces/acados_template/acados_template/generate_c_code_nls_cost.py#L101
it should be     `y_hess = Function(fun_name, [x, u, p, y], [ y_hess ])` instead of `y_hess = Function(fun_name, [x, u, p], [ y_hess ])` (y is missing).

Any thoughts on whether this is a correct solution?

**Comment by FreyJo** [comment]
Hi,

Thanks for reporting, you are completely right!
The cost function in the Python test is just a linear least squares function, that's why it wasn't found before..
I just added the fix to my open PR to get it merged quickly.
https://github.com/acados/acados/pull/573/commits/2378e05e41ed7c71bad2c7c2c89444cfc2e9e597

Cheers!
